# Generated by Django 5.2.6 on 2025-11-12 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='問題文')),
                ('answer', models.CharField(max_length=256, verbose_name='正解')),
                ('genre', models.CharField(blank=True, max_length=128, verbose_name='ジャンル')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, verbose_name='難易度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=256, verbose_name='回答')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解か')),
                ('ai_explanation', models.TextField(blank=True, verbose_name='Gemini解説')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='only_Kadai.question', verbose_name='問題')),
            ],
        ),
    ]
