# Generated by Django 5.2.6 on 2025-10-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work09', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='taskName',
            new_name='title',
        ),
    ]
