# Generated by Django 5.2.6 on 2025-10-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work09', '0002_rename_taskname_todo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
